/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: 'Montserrat',
      },
      colors: {
        color: '#008e7f',
        secondary: '#FFF9EE',
        dark: '#034694',
        light: '#87ceeb',
        'grey-light': '#F5F4F5',
        grey: '#C6D2DC',
        'grey-secondary': '#B6B5B6',
        white: '#fff',
        black: '#212224',
        'grey-dark': '#74776b',
        red: '#BA4425',
        green: '#30604A',
        olive: '#B7BDA4',
        gold: '#fbc130',
        silver: '#DADADA',
        bronze: '#BB7536',
        'blue-electric': '#2B59FF',
        blue: '#232A40',
        yellow: '#fbc130',
        'yellow-light': '#FFF9EE',
        'green-light': '#B7BDA4',
        'red-light': '#EDCDBF',
        'blue-light': '#C6D2DC',
        'shadow-gold': '#FFDA77',
        'shadow-silver': '#EDEDED',
        'shadow-bronze': '#6B431F',
        'shadow-blue': '#0776F8',
        'shadow-green': '#30604A',
        'shadow-black': '#212324',
        'shadow-secondary': 'rgb(183, 189, 164)',
        'shadow-red': 'rgb(186, 68, 37)',
        'shadow-green2': 'rgb(48, 96, 74)',
        dust: '#F5F4F5',
        quaternary: 'rgba(116, 116, 128, 0.08)',
      },
      fontSize: {
        xl: '21px',
      },
    },
  },
  plugins: [],
};
